inherit_from: .rubocop_todo.yml



#---------------------------
# Style configuration
#---------------------------

# Offense count: 169
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: true
  SpaceBeforeBlockParameters: false

# Cop supports --auto-correct.
Style/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space


#---------------------------
# Don't intend to fix these:
#---------------------------

# Cop supports --auto-correct.
# Reason: Double spaces can be useful for grouping code
Style/EmptyLines:
  Enabled: false

# Cop supports --auto-correct.
# Reason: I have very big opinions on this one.  See:
#   https://github.com/bbatsov/ruby-style-guide/issues/329
#   https://github.com/bbatsov/ruby-style-guide/pull/325
Style/NegatedIf:
  Enabled: false

# Cop supports --auto-correct.
# Reason: I'm fine either way on this, but could maybe be convinced that this should be enforced
Style/Not:
  Enabled: false

# Cop supports --auto-correct.
# Reason: I'm fine with this
Style/PerlBackrefs:
  Enabled: false

# Configuration parameters: Methods.
# Reason: We should be able to specify full variable names, even if it's only one line
Style/SingleLineBlockParams:
  Enabled: false

# Offense count: 1
# Reason: Switched `extend self` to `module_function` in id_property.rb but that caused errors
Style/ModuleFunction:
  Enabled: false
