inherit_from: .rubocop_todo.yml



#---------------------------
# Style configuration
#---------------------------

# Offense count: 169
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  EnforcedStyle: ruby19



#---------------------------
# Don't intend to fix these:
#---------------------------

# Offense count: 64
# Cop supports --auto-correct.
# Reason: Double spaces can be useful for grouping code
Style/EmptyLines:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Reason: I have very big opinions on this one.  See:
#   https://github.com/bbatsov/ruby-style-guide/issues/329
#   https://github.com/bbatsov/ruby-style-guide/pull/325
Style/NegatedIf:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Reason: I'm fine either way on this, but could maybe be convinced that this should be enforced
Style/Not:
  Enabled: false

