inherit_from: .rubocop_todo.yml



#---------------------------
# Style configuration
#---------------------------

# Offense count: 169
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  EnforcedStyle: ruby19



#---------------------------
# Don't intend to fix these:
#---------------------------

# Offense count: 64
# Cop supports --auto-correct.
# Reason: Double spaces can be useful for grouping code
Style/EmptyLines:
  Enabled: false

