script:
  - "travis_retry bundle exec rake neo4j:install[$NEO4J_VERSION] --trace"
  - "./db/neo4j/development/bin/neo4j console"
  - "sleep 10"
  - "travis_retry bundle exec rake default --trace"
language: ruby
cache: bundler
sudo: false
addons:
  artifacts:
    s3_region: "us-east-1"
    debug: true
    paths:
      - ./db/neo4j/development/logs/neo4j.log
      - ./db/neo4j/development/logs/debug.log
jdk:
  - oraclejdk8
rvm:
  - 2.3.0
  - 2.2.4
  - 2.0.0
  - jruby-1.7.23
  - jruby-9.0.4.0
env:
  global:
    - JRUBY_OPTS="-X+O -J-Djruby.launch.inproc=false -J-Xmx1024m -J-XX:MaxPermSize=2048m"
  matrix:
    - NEO4J_VERSION=community-3.0.1
    - NEO4J_VERSION=community-2.3.0
    - NEO4J_VERSION=community-2.2.6
    - NEO4J_VERSION=community-2.1.8
matrix:
  include:
    - rvm: 2.3.0
      script: "bundle exec rubocop"
      env: "RUBOCOP=true"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b803232e5210f6134a1e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
