---
dist: xenial
language: ruby
python:
  - 3.8
jdk:
  - openjdk11
cache: bundler
rvm:
  - 2.7.1
  - jruby-9.2.13.0
before_install:
  - wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py --user
  - python3 -m pip install --user git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
  - neoctrl-install $NEO4J_EDITION_FLAG $NEO4J_VERSION servers
  - if [ -n "$NEO4J_EDITION_FLAG" ]; then NEO4J_EDITION=enterprise; else NEO4J_EDITION=community; fi
  - NEO4J_DIR=servers/neo4j-$NEO4J_EDITION-$NEO4J_VERSION
  - neoctrl-configure $NEO4J_DIR dbms.memory.pagecache.size=600m dbms.memory.heap.max_size=600m dbms.memory.heap.initial_size=600m dbms.directories.import= dbms.security.auth_enabled=false
   #dbms.connectors.default_listen_address=::
install:
  - neoctrl-start $NEO4J_DIR
  - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-16.04.deb
  - sudo dpkg -i seabolt-1.7.4-Linux-ubuntu-16.04.deb
env:
  global:
    - JRUBY_OPTS="--debug -J-Xmx1280m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF"
    - NEO4J_EDITION_FLAG=-e
    - NEO4J_BOLT_URL="bolt://127.0.0.1:7687"
    - PATH=$PATH:~/.local/bin
  matrix:
    - NEO4J_VERSION=3.5.25
    - NEO4J_VERSION=4.0.10
matrix:
  include:
    # Testing older versions of ActiveModel
    - rvm: 2.5.8
      jdk: openjdk8
      env: NEO4J_VERSION=3.4.18 ACTIVE_MODEL_VERSION=5.2.3 NEO4J_EDITION_FLAG=

    - rvm: jruby-9.2.13.0
      env: driver=java NEO4J_VERSION=4.0.10
